In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import glob
%matplotlib inline

In [65]:
os.getcwd()

'C:\\Users\\PRECIOUS\\Documents\\pratice'

In [66]:
os.chdir('C:\\Users\\PRECIOUS\\Documents')

In [67]:
os.getcwd()

'C:\\Users\\PRECIOUS\\Documents'

In [68]:
os.mkdir('pratice')

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'pratice'

In [69]:
os.chdir('C:\\Users\\PRECIOUS\\Documents\\pratice')

In [70]:
os.getcwd()

'C:\\Users\\PRECIOUS\\Documents\\pratice'

In [97]:
data= pd.read_csv('we.csv')
data

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [98]:
data.columns

Index(['year', 'artist.inverted', 'track', 'time', 'genre', 'date.entered',
       'date.peaked', 'x1st.week', 'x2nd.week', 'x3rd.week', 'x4th.week',
       'x5th.week', 'x6th.week', 'x7th.week', 'x8th.week', 'x9th.week',
       'x10th.week', 'x11th.week', 'x12th.week', 'x13th.week', 'x14th.week',
       'x15th.week', 'x16th.week', 'x17th.week', 'x18th.week', 'x19th.week',
       'x20th.week', 'x21st.week', 'x22nd.week', 'x23rd.week', 'x24th.week',
       'x25th.week', 'x26th.week', 'x27th.week', 'x28th.week', 'x29th.week',
       'x30th.week', 'x31st.week', 'x32nd.week', 'x33rd.week', 'x34th.week',
       'x35th.week', 'x36th.week', 'x37th.week', 'x38th.week', 'x39th.week',
       'x40th.week', 'x41st.week', 'x42nd.week', 'x43rd.week', 'x44th.week',
       'x45th.week', 'x46th.week', 'x47th.week', 'x48th.week', 'x49th.week',
       'x50th.week', 'x51st.week', 'x52nd.week', 'x53rd.week', 'x54th.week',
       'x55th.week', 'x56th.week', 'x57th.week', 'x58th.week', 'x59th.week',
       'x60th.week', 'x61st.week', 'x62nd.week', 'x63rd.week', 'x64th.week',
       'x65th.week', 'x66th.week', 'x67th.week', 'x68th.week', 'x69th.week',
       'x70th.week', 'x71st.week', 'x72nd.week', 'x73rd.week', 'x74th.week',
       'x75th.week', 'x76th.week'],
      dtype='object')

In [99]:
smalldata = data[['artist.inverted', 'track', 'time', 'date.entered'
       , 'x1st.week', 'x2nd.week', 'x3rd.week']]

In [100]:
smalldata

,artist.inverted,track,time,date.entered,x1st.week,x2nd.week,x3rd.week
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,78,63.0,49.0
1,Santana,"Maria, Maria",4:18,2000-02-12,15,8.0,6.0
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,71,48.0,43.0
3,Madonna,Music,3:45,2000-08-12,41,23.0,18.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,57,47.0,45.0
...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,98,NaN,NaN
313,"Smith, Will",Freakin' It,3:58,2000-02-12,99,99.0,99.0
314,Zombie Nation,Kernkraft 400,3:30,2000-09-02,99,99.0,NaN
315,"Eastsidaz, The",Got Beef,3:58,2000-07-01,99,99.0,NaN
316,Fragma,Toca's Miracle,3:22,2000-10-28,99,NaN,NaN

In [101]:
smalldata.columns=['artist','track', 'time','date.entered','wk1', 'wk2', 'wk3']

In [102]:
smalldata

,artist,track,time,date.entered,wk1,wk2,wk3
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,78,63.0,49.0
1,Santana,"Maria, Maria",4:18,2000-02-12,15,8.0,6.0
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,71,48.0,43.0
3,Madonna,Music,3:45,2000-08-12,41,23.0,18.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,57,47.0,45.0
...,...,...,...,...,...,...,...
312,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,98,NaN,NaN
313,"Smith, Will",Freakin' It,3:58,2000-02-12,99,99.0,99.0
314,Zombie Nation,Kernkraft 400,3:30,2000-09-02,99,99.0,NaN
315,"Eastsidaz, The",Got Beef,3:58,2000-07-01,99,99.0,NaN
316,Fragma,Toca's Miracle,3:22,2000-10-28,99,NaN,NaN

In [103]:
smelt = smalldata.melt(['artist','track', 'time','date.entered'], ['wk1', 'wk2', 'wk3'], 'wks', 'rate')

In [104]:
smelt

,artist,track,time,date.entered,wks,rate
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,wk1,78.0
1,Santana,"Maria, Maria",4:18,2000-02-12,wk1,15.0
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,wk1,71.0
3,Madonna,Music,3:45,2000-08-12,wk1,41.0
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,wk1,57.0
...,...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,wk3,NaN
947,"Smith, Will",Freakin' It,3:58,2000-02-12,wk3,99.0
948,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk3,NaN
949,"Eastsidaz, The",Got Beef,3:58,2000-07-01,wk3,NaN
950,Fragma,Toca's Miracle,3:22,2000-10-28,wk3,NaN

In [105]:
smelt['wk'] = smelt['wks'].apply(lambda X : int(X[2]))

In [80]:
smelt

,artist,track,time,date.entered,wks,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,wk1,78.0,1
1,Santana,"Maria, Maria",4:18,2000-02-12,wk1,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,wk1,71.0,1
3,Madonna,Music,3:45,2000-08-12,wk1,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,wk1,57.0,1
...,...,...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,wk3,NaN,3
947,"Smith, Will",Freakin' It,3:58,2000-02-12,wk3,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,2000-09-02,wk3,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,2000-07-01,wk3,NaN,3
950,Fragma,Toca's Miracle,3:22,2000-10-28,wk3,NaN,3

In [106]:
smelt.drop(['wks'], axis=1, inplace=True)

In [107]:
smelt

,artist,track,time,date.entered,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,78.0,1
1,Santana,"Maria, Maria",4:18,2000-02-12,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,71.0,1
3,Madonna,Music,3:45,2000-08-12,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,57.0,1
...,...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,NaN,3
947,"Smith, Will",Freakin' It,3:58,2000-02-12,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,2000-09-02,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,2000-07-01,NaN,3
950,Fragma,Toca's Miracle,3:22,2000-10-28,NaN,3

In [108]:
smelt['date.entered']= pd.to_datetime(smelt['date.entered'])

In [109]:
smelt

,artist,track,time,date.entered,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,2000-09-23,78.0,1
1,Santana,"Maria, Maria",4:18,2000-02-12,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23,71.0,1
3,Madonna,Music,3:45,2000-08-12,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05,57.0,1
...,...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05,NaN,3
947,"Smith, Will",Freakin' It,3:58,2000-02-12,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,2000-09-02,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,2000-07-01,NaN,3
950,Fragma,Toca's Miracle,3:22,2000-10-28,NaN,3

In [110]:
smelt['date.entered'][0] = pd.to_timedelta("7days")

C:\Users\PRECIOUS\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\PRECIOUS\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [111]:
smelt

,artist,track,time,date.entered,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,7 days 00:00:00,78.0,1
1,Santana,"Maria, Maria",4:18,2000-02-12 00:00:00,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,1999-10-23 00:00:00,71.0,1
3,Madonna,Music,3:45,2000-08-12 00:00:00,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,2000-08-05 00:00:00,57.0,1
...,...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,2000-08-05 00:00:00,NaN,3
947,"Smith, Will",Freakin' It,3:58,2000-02-12 00:00:00,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,2000-09-02 00:00:00,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,2000-07-01 00:00:00,NaN,3
950,Fragma,Toca's Miracle,3:22,2000-10-28 00:00:00,NaN,3

In [93]:
date=smelt['date.entered'] +pd.to_timedelta('0days')*(smelt['wk'])

KeyError: 'date.entered'

In [94]:
smelt

,artist,track,time,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,78.0,1
1,Santana,"Maria, Maria",4:18,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,71.0,1
3,Madonna,Music,3:45,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,57.0,1
...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,NaN,3
947,"Smith, Will",Freakin' It,3:58,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,NaN,3
950,Fragma,Toca's Miracle,3:22,NaN,3

In [95]:
smelt.drop(['date.entered'], axis=1,inplace=True)

KeyError: "['date.entered'] not found in axis"

In [96]:
smelt

,artist,track,time,rate,wk
0,Destiny's Child,Independent Women Part I,3:38,78.0,1
1,Santana,"Maria, Maria",4:18,15.0,1
2,Savage Garden,I Knew I Loved You,4:07,71.0,1
3,Madonna,Music,3:45,41.0,1
4,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,57.0,1
...,...,...,...,...,...
946,Ghostface Killah,Cherchez LaGhost,3:04,NaN,3
947,"Smith, Will",Freakin' It,3:58,99.0,3
948,Zombie Nation,Kernkraft 400,3:30,NaN,3
949,"Eastsidaz, The",Got Beef,3:58,NaN,3
950,Fragma,Toca's Miracle,3:22,NaN,3